config/routes.rb
Rails.application.routes.draw do
  get 'bienvenido/index'  
  root 'bienvenido#index'

  resources :articulos do
    resources :comentarios
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/articulo.rb
class Articulo < ApplicationRecord
    has_many :comentarios, dependent: :destroy
    validates :title, presence: true, length: { minimum: 5 }
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :articulo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
    http_basic_authenticate_with name: "fran", password: "123", except: [:index, :show] 
    def index
        @articulos = Articulo.all
    end

    def show
        @articulo = Articulo.find(params[:id])
    end

    def new
        @articulo = Articulo.new
    end

    def edit
        @articulo = Articulo.find(params[:id])
    end

    def create
        @articulo = Articulo.new(articulo_params)
        if @articulo.save
            redirect_to @articulo
        else
            render 'new'
        end
       #render plain: params[:articulo]
    end

    def update 
        @articulo = Articulo.find(params[:id])
        if @articulo.update(articulo_params)
            redirect_to @articulo
        else
            render 'edit'
        end
    end
    
    def destroy
        @articulo = Articulo.find(params[:id])
        @articulo.destroy
        redirect_to articulos_path
    end
    
    private
    def articulo_params
      params.require(:articulo).permit(:title, :text)
    end
end

app/controllers/bienvenido_controller.rb
class BienvenidoController < ApplicationController
  def index
  end
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
    http_basic_authenticate_with name: "fran", password: "123", only: :destroy
    def create
        @articulo = Articulo.find(params[:articulo_id])
        @comentario = @articulo.comentarios.create(comentario_params)
        redirect_to articulo_path(@articulo)
    end
    
    def destroy
        @articulo = Articulo.find(params[:articulo_id])
        @comentario = @articulo.comentarios.find(params[:id])
        @comentario.destroy
        redirect_to articulo_path(@articulo)
    end

    private
        def comentario_params
            params.require(:comentario).permit(:commenter, :body)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/articulos/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
  <% if @articulo.errors.any? %>
    <div id="error_explsnstion">
      <h2><%= pluralize(@articulo.errors.count, "error")%> al guardar el articulo</h2>
      <ul>
        <%= @articulo.errors.full_messages.each do |msg|%>
          <li> <%= msg %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= form.label :Titulo %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :Contenido %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit 'Guardar' %>
  </p>
<% end %>

app/views/articulos/edit.html.erb
<h1>Editar Articulo</h1>

<%= form_with(model: @articulo, local: true) do |form| %>
  <% if @articulo.errors.any? %>
    <div id="error_explsnstion">
      <h2><%= pluralize(@articulo.errors.count, "error")%> al guardar el articulo</h2>
      <ul>
        <%= @articulo.errors.full_messages.each do |msg|%>
          <li> <%= msg %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= form.label :Titulo %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :Contenido %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit 'Guardar' %>
  </p>
<% end %>

<%= link_to 'Volver', articulos_path %>

app/views/articulos/index.html.erb
<h1>Lista de Articulos</h1>

<%= link_to 'Nuevo Articulo', new_articulo_path %>

<table>
    <tr>
        <th>Titulos</th>
        <th>Contenido</th>
        <th>/</th>
    </tr>
    <% @articulos.each do |articulo|%>
        <tr>
            <td> <%= articulo.title %> </td>
            <td> <%= articulo.text %> </td>
            <td> <%= link_to 'Ver', articulo_path(articulo) %> </td>            
            <td><%= link_to 'Editar', edit_articulo_path(articulo) %></td>
            <td><%= link_to 'Borrar', articulo_path(articulo), method: :delete, data:{confirm: 'SegurE?'} %></td>
        </tr>
    <% end %>
</table>

app/views/articulos/new.html.erb
<h1>Nuevo Articulo</h1>
<%= form_with scope: :articulo, url: articulos_path, local: true do |form| %>
  <% if @articulo.errors.any? %>
    <div id="error_explsnstion">
      <h2><%= pluralize(@articulo.errors.count, "error")%> al guardar el articulo</h2>
      <ul>
        <%= @articulo.errors.full_messages.each do |msg|%>
          <li> <%= msg %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= form.label :Titulo %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :Contenido %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit 'Guardar' %>
  </p>
<% end %>
<%= link_to 'Volver', articulos_path %>

app/views/articulos/show.html.erb
<h1>Articulo:</h1>
<p>
    <strong>Titulo:</strong>
    <%= @articulo.title%>
</p>
<p>
    <strong>Contenido:</strong>
    <%= @articulo.text%>
</p>

<%= link_to 'Editar', edit_articulo_path(@articulo) %>

<h2>Añadir un comentario:</h2>
<%= render 'comentarios/form' %>


<h2>Comentarios</h2>
<%= render @articulo.comentarios %>

<%= link_to 'Volver', articulos_path %>

app/views/bienvenido/index.html.erb
<h1>Holis</h1>
<%= link_to 'Mi blog', controller: 'articulos'%>

app/views/comentarios/_comentario.html.erb
  <p>
    <strong>De:</strong>
    <%= comentario.commenter %>
  </p>
 
  <p>
    <strong>Comentario:</strong>
    <%= comentario.body %>
  </p>
<p>
  <%= link_to 'Borrar comentario', [comentario.articulo, comentario], method: :delete, data: {confirm: 'SegurE?'} %>
</p>

app/views/comentarios/_form.html.erb
<%= form_for([@articulo, @articulo.comentarios.build]) do |form|%>
<p>
    <%= form.label :Nombre %><br>
    <%= form.text_field :commenter %>
</p>
<p>
    <%= form.label :Mensaje %><br>
    <%= form.text_area :body%>
</p>
<p>
    <%= form.submit 'Enviar Comentario'%>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>